version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - HTTP_ADDR=0.0.0.0
      - HTTP_PORT=8080
      - PG_DSN=postgres://user:password@postgres:5432/app?sslmode=disable
      - REDIS_ADDR=redis:6379
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    secrets:
      - jwt_secret

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:

secrets:
  jwt_secret:
    file: ./jwt.secret
