// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: inference_logs.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

const createInferenceLog = `-- name: CreateInferenceLog :exec
INSERT INTO inference_logs (
  user_id, api_key_id, request_payload, response_payload, error, request_time, response_time
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
`

type CreateInferenceLogParams struct {
	UserID          int64                 `json:"user_id"`
	ApiKeyID        sql.NullInt64         `json:"api_key_id"`
	RequestPayload  json.RawMessage       `json:"request_payload"`
	ResponsePayload pqtype.NullRawMessage `json:"response_payload"`
	Error           sql.NullString        `json:"error"`
	RequestTime     time.Time             `json:"request_time"`
	ResponseTime    time.Time             `json:"response_time"`
}

func (q *Queries) CreateInferenceLog(ctx context.Context, arg CreateInferenceLogParams) error {
	_, err := q.db.ExecContext(ctx, createInferenceLog,
		arg.UserID,
		arg.ApiKeyID,
		arg.RequestPayload,
		arg.ResponsePayload,
		arg.Error,
		arg.RequestTime,
		arg.ResponseTime,
	)
	return err
}
