// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ApiKey struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	KeyHash    []byte         `json:"key_hash"`
	Label      sql.NullString `json:"label"`
	Active     bool           `json:"active"`
	RateRpm    int32          `json:"rate_rpm"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type InferenceLog struct {
	ID              int64                 `json:"id"`
	UserID          int64                 `json:"user_id"`
	ApiKeyID        sql.NullInt64         `json:"api_key_id"`
	RequestPayload  json.RawMessage       `json:"request_payload"`
	ResponsePayload pqtype.NullRawMessage `json:"response_payload"`
	Error           sql.NullString        `json:"error"`
	RequestTime     time.Time             `json:"request_time"`
	ResponseTime    time.Time             `json:"response_time"`
	CreatedAt       time.Time             `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Plan         string    `json:"plan"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Name         string    `json:"name"`
}
