// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type ApiKey struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	KeyHash    []byte         `json:"key_hash"`
	Label      sql.NullString `json:"label"`
	Active     bool           `json:"active"`
	RateRpm    int32          `json:"rate_rpm"`
	LastUsedAt sql.NullTime   `json:"last_used_at"`
	CreatedAt  time.Time      `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Plan         string    `json:"plan"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	Name         string    `json:"name"`
}
